---
- name: Start procps
  ansible.builtin.systemd:
    name: procps
    state: started
    daemon_reload: true

- name: Reload haproxy demo-haproxy
  ansible.builtin.systemd:
    name: "demo-haproxy"
    state: reloaded
    daemon_reload: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: "rsyslog"
    state: restarted
    daemon_reload: true
